#.config/kitty/kitty.conf
# setup kitty to default terminal: sudo update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator $(which kitty) 50

cursor_trail 1
cursor_trail_decay 0.1 0.5

font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

window_padding_width 0
hide_window_decorations yes
placement_strategy center
resize_debounce_time 0.1
resize_in_steps no
background #1e1e2e
color1 #ff5555
color9 #ff2b2b

font_size 10.0

map ctrl+shift+t new_tab_with_cwd
map ctrl+f2 detach_window
map ctrl+f3 detach_window new-tab
map ctrl+f4 detach_window ask
allow_remote_control true

