vim.api.nvim_create_user_command("CopyFilename", function()
  local filename = vim.fn.expand("%:t")
  vim.fn.setreg("+", filename)
  vim.notify("Copied filename: " .. filename)
end, {})

vim.api.nvim_create_user_command("CopyAbsolutePath", function()
  local abs_path = vim.fn.expand("%:p")
  vim.fn.setreg("+", abs_path)
  vim.notify("Copied absolute path: " .. abs_path)
end, {})

vim.api.nvim_create_user_command("CopyRelativePath", function()
  local rel_path = vim.fn.expand("%:.")
  vim.fn.setreg("+", rel_path)
  vim.notify("Copied relative path: " .. rel_path)
end, {})
